In [19]:
import pandas as pd

df = pd.read_html("https://fbref.com/en/squads/b8fd03ef/Manchester-City-Stats", header=1)
df[10].head()

,Player,Nation,Pos,Age,MP,Min,Mn/MP,Min%,90s,Starts,...,onGA,+/-,+/-90,On-Off,onxG,onxGA,xG+/-,xG+/-90,On-Off.1,Matches
0,Ederson,br BRA,GK,26.0,36,3240.0,90.0,94.7,36.0,36,...,28.0,48.0,1.33,-0.17,69.7,28.4,41.2,1.15,0.79,Matches
1,Rúben Dias,pt POR,DF,23.0,32,2843.0,89.0,83.1,31.6,32,...,21.0,47.0,1.49,0.86,61.3,23.6,37.7,1.19,0.53,Matches
2,Rodri,es ESP,MF,24.0,34,2748.0,81.0,80.4,30.5,31,...,27.0,37.0,1.21,-0.66,60.5,25.6,34.8,1.14,0.18,Matches
3,Raheem Sterling,eng ENG,FW,25.0,31,2536.0,82.0,74.2,28.2,28,...,23.0,35.0,1.24,-0.39,56.6,23.7,32.8,1.16,0.24,Matches
4,João Cancelo,pt POR,DF,26.0,28,2299.0,82.0,67.2,25.5,27,...,18.0,33.0,1.29,-0.15,53.2,19.4,33.8,1.32,0.67,Matches